name: dependent-gems-test

on:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [ pre-release, pre-integration-tests ]

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3

    - id: build-matrix
      run: |
        wget https://raw.githubusercontent.com/metanorma/ci/main/.github/workflows/ruby-matrix.json
        # remove 'middle' & 'experimental' versions
        echo "$(jq 'del(.ruby[1, 3])' ruby-matrix.json)" > ruby-matrix.json

        echo "matrix=$(jq -s add .github/workflows/dependent-flavors.json ruby-matrix.json | tr '\n' ' ')" >> $GITHUB_OUTPUT

  rake:
    name: Test dependent gem relaton-${{ matrix.flavor }} ${{ matrix.ruby.version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs:
    - build-matrix

    concurrency:
      group: 'relaton-${{ matrix.flavor }}-${{ matrix.os }}-${{ matrix.ruby.version }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true

    continue-on-error: ${{ matrix.experimental || matrix.ruby.experimental }}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/checkout@v3
      with:
        submodules: recursive
        repository: relaton/relaton-${{ matrix.flavor }}
        path: dependent
        fetch-depth: 1

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby.version }}
        rubygems: ${{ matrix.ruby.rubygems }}
        bundler-cache: true
        working-directory: dependent

    - name: Replace rubygems's relaton-index with github's one
      shell: python
      run: |
        import fileinput
        import sys
        import os
        print("Python version:", sys.version)
        with fileinput.FileInput('relaton_${{ matrix.flavor }}.gemspec', inplace=True) as file:
          for line in file:
            if 'relaton-index' not in line:
              print(line, end='')
        print("'relaton-index' removed from relaton_${{ matrix.flavor }}.gemspec")
        if os.path.exists("Gemfile.lock"):
          os.remove("Gemfile.lock")
          print("Gemfile.lock dropped")
        print("> git diff")
        sys.stdout.flush()
        os.system("git diff")
        print("> bundle add relaton-index --path ..")
        sys.stdout.flush()
        os.system("bundle add relaton-index --path ..")
      working-directory: dependent

    - run: bundle exec rake
      working-directory: dependent

  tests-passed:
    needs: rake
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v3
        name: Tests passed
        with:
          token: ${{ secrets.RELATON_CI_PAT_TOKEN || github.token }}
          repository: ${{ github.repository }}
          event-type: tests-passed
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "type": "tests-passed"}'

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Repository ready for release
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.RELATON_CI_PAT_TOKEN || github.token }}
          repository: ${{ github.repository }}
          event-type: do-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "type": "do-release"}'
