name: dependent-gems-test

on:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [ pre-release, integration-tests ]

jobs:
  rake:
    uses: metanorma/ci/.github/workflows/dependent-rake.yml@main

  tests-passed:
    needs: rake
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v3
        name: Tests passed
        with:
          token: ${{ secrets.RELATON_CI_PAT_TOKEN || github.token }}
          repository: ${{ github.repository }}
          event-type: tests-passed
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "type": "tests-passed"}'

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Repository ready for release
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.RELATON_CI_PAT_TOKEN || github.token }}
          repository: ${{ github.repository }}
          event-type: do-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "type": "do-release"}'
