name: rake

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  rake:
    uses: relaton/support/.github/workflows/rake.yml@main
    with:
      tests-passed-event: integration-tests
      release-event: pre-release
